### ISSUE TITLE
[SUGGESTION] WZS Hardmode: Plentiful of fixes to improve it

### ISSUE THREAD

**Issue by CWorm** [Azurblau/Zombies.Zone#105]
1: Require minimal level to join server; the issue with server no.3 is that it's intended for veteran players, yet it's difficult for them to play with kleiners which join freshly to the WZS, unfamiliar with mechanics they often are less than useful for players (ie. asking why they cannot cade or camping in final cade). Even when they don't contribute to zombie number, often when they die they either leave the server or 

Suggestion: Minimal level of 30, if connecting player is below that, redirect them randomly to no.1 or no.2

2: Human bots; they were supposed to be a beneficial towards humans but in most cases players don't care about them too much, causing them to die on zombies and even if they don't, they contribute to higher number of zombies, bots follow idle/wandering players that don't attack zombies so these bots just make the gamemode harder.

Suggestion: Remove human bots and add them only as an event feature OR to be added through ULX.

3: Health regen; zombies regenerate health way too fast, making it very difficult to put zmain zombies which can harass players with classes like Fresh Dead

Suggestion: Remove health regen BUT add a special zombie which acts like a mini-sphynx

4: Extra XP: Not too much being said here, but considering how many points are gained on WZS Hardmode, it's still less than what is gained on ie. no.1 or no.2

Suggestion: Increase extra XP even more

I get that casual players are reason why WZS became popular, but I fail to see why no.3 should be catered to them as well, considering there are two casual servers already. I feel like players would like to have a difficult server that requires cooperation but simply these aspects make server unsatisfactory to play it on.

**Comment by UrNibba** [comment]
Sounds really cool +1

**Comment by v1red** [comment]
1.... I think level 40 or more will be ok for veterans
2.... When I join on server #3 there are like 2 3 players. If they have experience i give the boots to them if no i get them to defend while im cading. Getting rid of them its pointless they are more than usefull if you use them right. 
3.... The regen healt. Fucking hell took me like 2 minutes to kill a zombie with an axe. What will i do will be to give them some extra 100 200 hp and no regen considering its hard mode and mini spinx hmm... mabye just make u dizzy when hits u not from the distance. U can make mummy zombie having this trait sience i haven't see any players using it.
4. U can't make enough xp for a good weapon. I've try everything melle, smg, pistol etc. Best current thing to do its cading get boots to defend and u repair. Some extra points will be great consindering the difficulty.

Server 3 should be more like a team play. A medic defenders someone to cade repair etc... you ask for opinion, this it's mine

**Comment by CWorm** [comment]
That's cool v1red, I appreciate your input. With 4th point I meant that exp should be increased further for everything, not just guns.

**Comment by Azurblau** [comment]
Health regen got nerfed from 2% per second to 0.5% per second.

**Comment by Azurblau** [comment]
Fixed hard mode actually giving less experience than easy mode. Exp is now 2.5 per point instead of the 1.25 per point (easy mode has 1 per point but in hard mode rewarded points are halved).

**Comment by Azurblau** [comment]
Each human bot now counts as 25% of a person, was 50% before. This number determines how much they influence zombie count. (E.g. 4 human bots equal to 1 player when it comes to calculating the number of zombies)

**Comment by v1red** [comment]
https://imgur.com/N4lCtil
https://imgur.com/2LDGz7i 
Please make level 50 + on hard mode.I spend like 3 hrs today and the the highest level of a player was 19...

**Comment by Azurblau** [comment]
Minimum level for hard mode is 30 now. If that isn't enough, please open a new issue.
