### ISSUE TITLE
[SUGGESTION] WZS: Change turret targeting

### ISSUE THREAD

**Issue by HoneyBadger1337** [Azurblau/Zombies.Zone#107]
I've noticed that the way the turret targets is a bit unusual, in that the targeting laser moves even if it's currently got a target.

This means that most times, unless the zombie is right in front of the turret, it'll just shoot a bullet, then go back to just searching for a new target, instead of focusing on that target until it dies or goes out of it's range.

So I think instead, the turret targeting system should be changed to instead focus on the one zombie that crosses it's laser until it dies or goes outside it's targeting range.

**Comment by Azurblau** [comment]
I've improved it a bit, but it's not perfect yet. Should the new method not be effective enough, feel free to open a new ticket.
