### ISSUE TITLE
[SUGGESTION] WZS: Add a path to roofs from train cars on zs_scrapmetal

### ISSUE THREAD

**Issue by h4uja2** [Azurblau/Zombies.Zone#110]
I think there should be another way to roof - so I  suggest removing/making breakable/replacing these boards to give players a way to roofs. It still will be situational and risky because of being very close to zspawn.
 Sorry for my paint skills. ![20180405152610_2](https://user-images.githubusercontent.com/22843252/38372597-e5d12f5e-38f7-11e8-95d2-d55a4a9205db.png) (also example of windows that are breakable)

**Comment by CWorm** [comment]
It's already possible to go there, you need to jump on the sign and the planks are breakable.
