### ISSUE TITLE
[SUGGESTION] WZS: Medic Suggestions

### ISSUE THREAD

**Issue by nibbyy** [Azurblau/Zombies.Zone#118]
Got a few suggestions for Medic:

_- People who are full (or over 90%?) do NOT have an aura when you have your medkit out. Like I said on Discord, currently it can be difficult to tell who needs healing unless they are under 50 HP or you're paying attention to their numbers._ (Already added)

- Healing others heals yourself for a small amount (25%?)
- A small message that pops up when you heal someone telling you how much you healed for. After getting a few increases to healing, it becomes very difficult to tell how much you're healing for. Seeing an actual number would be very nice. As well, whenever you get healed a small message that tells you who healed you and for how much.
- Increase the range on medkits by a small amount. Running around chasing after people trying to heal them is NOT fun.
- Change the icon above medics heads from the green "+" to something else. Maybe a red cross or even just the word "MEDIC" would be a lot more obvious for players to run to you for healing.

That's all. Thanks.

**Comment by Aquid0** [comment]
+1

**Comment by nibbyy** [comment]
edit: they added one of my suggestions!

**Comment by Azurblau** [comment]
Forgot to mention the change here. Yes, humans above 90% now appear as blue. The other suggestions are still open.

**Comment by nibbyy** [comment]
Two things;
- If increasing range on medkit is not possible, instead give increased movement speed with the medkit out
- Could also give medkits a red cross at their feet (like the green friend circle) if changing the current icon is not appealing

**Comment by Azurblau** [comment]
Done all but the medic cross changes.
