### ISSUE TITLE
[SUGGESTION] WZS: Better Healing "Icon" & Knife Item Fix

### ISSUE THREAD

**Issue by FloZS** [Azurblau/Zombies.Zone#119]
## Hello people,
Just to be quick, I've thought about two ideas:

- Create a new Medic icon, a light blue or red circle under the players, like the "friends-indicator" (to 
   replace the current one who's over the peoples heads). It would more fit into the WZS design and the 
   icon right now looks a bit boring

- Make the knife "solid" in the items menu, so people can't throw it out of the inventory and remove the 
   fists for that, to make the knife to a permanent standard equipment like these fists before

To the knife idea: I often see a lot of knifes just laying on the floor. Of course, they despawn after a time or a special amout of items, but I think it could safe some small fps and other server resources. It also looks more cleaner when there aren't like 10 knifes around the barricades.

Have a nice day :)

**Comment by TheFray89** [comment]
I love that!
+1

**Comment by WardenPotato** [comment]
I see no point in the first one and for the second i would just remove the knife on drop.

**Comment by nibbyy** [comment]
First one I've suggested, too. Would like to see a new medic symbol so people can spot medics out of a crowd.

**Comment by Azurblau** [comment]
Knifes can be sold in the second hand shop now. For the medic icon I'll reference #118 so your suggestion appears there, too. If the issue is still prevalent (aka no janitors willing to earn 1 point per looted knife), please open another issue.
