### ISSUE TITLE
[SUGGESTION] WZS: Headcrab Boss

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#123]
I have personally thought about this Boss for a long time, and now I have clear ideas to create one who can work properly (yes, I want to create it myself)
a headcrab with about 1000 hp with red color able to cross underground like a normal headcrab, with the only difference that can cross also the barricades.
this means that this headcrab will be able to attack humans by surprise and then hide in case it is wounded. there will be a sort of countdown that will start once the headcrab goes underground and can not go underground again until the bar is loaded.

Thats my actual stats:

- Health = 800
- Speed = 250
- JumpPower = 280
- Damage = 20 
- Ability can cross to the barricades when its underground

I want to know your opinions, what you would like to change and especially what you dont like and that you would like to improve.

**Comment by CWorm** [comment]
Very generic idea, there is nothing special about a big headcrab, a boss should be something that stands out from regular zombies, not just to be a 'biggified' version of something.

**Comment by TheFray89** [comment]
as I said before, I'm going to add to this boss a special mechanic with a timer that make to make it useful and not too powerful.
As for the headcrab measures, I was not going to make a giant headcrab, it had to remain its normal measurements
