### ISSUE TITLE
[SUGGESTION] WZS: arsenal crate issue

### ISSUE THREAD

**Issue by Mauro-the-Wizard** [Azurblau/Zombies.Zone#127]
When someone dies, he leaves some loot behind. You can pick up arsenal crate which player had, but you can't place it. 
I tried to place it everywhere, but it didn't work. Pladvoded tried to place it also, but same thing again. 
This little bug happend to me already few times.

**Comment by h4uja2** [comment]
Correct me if I'm wrong, you need to pick up both arsenal crates, one of them is "weapon" and second is "ammo".
