### ISSUE TITLE
[SUGGESTION] CADER CLASS AND LOOTING CHANGE

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#133]
Make a class or a trait that allows you to hold a Hammer. Maybe combine it with muscular or something similiar. For example you can not pickup or hold a Carpenters Hammer without that trait, meaing you cant cade without it. (People could still hold nails tho)

This trait could be a 5 Point trait maybe or even a class for a hundred (100) points 
(Muscular, Hammer, 2 or 3 sets of nails and maybe something else from the spare points)

This would have to be either a trait you can get after redeeming or a class that reapplies after you died, meaning either be a cheap trait or a 100 point class that reapplies after death.

This would ATLEAST provet kleiners to take (electrohammers/Hammers) away from professional caders when they die in the cade or outside of it untill they redeem themself quickly or another player (if it is a trait) buys the trait to pick up the hammer. Because 4 out of 10 Games a map is wasted because the cader dies to something and cant cade after redeeming because a kleiner took everything and doesnt even know what the fuck to do with it all and ignores chat/voice chat.

Looting Change:

Apply a limit of items for each type would provent players to mass-loot those who just died.
Example only allow a player to hold up to 1 primary and 1 secondary (These numbers can be changed)
The "Horder" trait could play a role here and enable the  player to hold 2 primaries and secoundaries.
This change should not apply to Food ofc. This may or may not affect melee weapons too!
(We would have to watch out for crafting not to cause crashes/buggs tho)

Another nice change would be if you could HOLD E to switch between the weapon/tool on the ground with the one you are holding in your hand.

The ideas above could change and numbers aswell, this is just a raw idea of how we could provent Looters. Because this is starting to become a problem slowly, why?
Professinal caders and also those few Bouncers who actually care about cading and playing ZS as intended get furstrated often by the fact that once they die, they will have to start all over with nothing but 25 points, only enought to buy a hammer but nothing else. These points could have been spent on ammo or nails if the cader got their hammer back wich almost never happens because clueless players loot everything they see. But the problem is that these caders often avoid cading and just go Zmain most of the time wich also affects alot of Bouncers where are usually ment to help new players and teach them the game abit here and there, not to wreck their butts on everymap. (I am not saying any names here and I know its not just Bouncers who do that, its just something I personally see alot of the time. And I can understand that, I for myself often dont want to cade bc of that and because these kleiners dont even repair cades when they have a powersledge/hammer and you tell them to repair and how.

**Comment by CWorm** [comment]
Please split the ideas into two separate tickets.
