### ISSUE TITLE
[SUGGESTION] WZS: Cader class change

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#134]
Make a class or a trait that allows you to hold a Hammer. Maybe combine it with muscular or something similiar. For example you can not pickup or hold a Carpenters Hammer without that trait, meaing you cant cade without it. (People could still hold nails tho)

This trait could be a 5 Point trait maybe or even a class for a hundred (100) points
(Muscular, Hammer, 2 or 3 sets of nails and maybe something else from the spare points)

This would have to be either a trait you can get after redeeming or a class that reapplies after you died, meaning either be a cheap trait or a 100 point class that reapplies after death.

This would ATLEAST provet kleiners to take (electrohammers/Hammers) away from professional caders when they die in the cade or outside of it untill they redeem themself quickly or another player (if it is a trait) buys the trait to pick up the hammer. Because 4 out of 10 Games a map is wasted because the cader dies to something and cant cade after redeeming because a kleiner took everything and doesnt even know what the fuck to do with it all and ignores chat/voice chat.

**Comment by mikan1216** [comment]
+1

**Comment by CWorm** [comment]
I don't like idea of overly complicating WZS casual especially it's going to buff humans indirectly similar to #135 - if you die, there should be a penalty for it.
