### ISSUE TITLE
[SUGGESTION] WZS: Looting Change

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#135]
Looting Change:

Apply a limit of items for each type would provent players to mass-loot those who just died.
Example only allow a player to hold up to 1 primary and 1 secondary (These numbers can be changed)
The "Horder" trait could play a role here and enable the player to hold 2 primaries and secoundaries.
This change should not apply to Food ofc. This may or may not affect melee weapons too!
(We would have to watch out for crafting not to cause crashes/buggs tho)

Another nice change would be if you could HOLD E to switch between the weapon/tool on the ground with the one you are holding in your hand.

The ideas above could change and numbers aswell, this is just a raw idea of how we could provent Looters. Because this is starting to become a problem slowly, why?
Professinal caders and also those few Bouncers who actually care about cading and playing ZS as intended get furstrated often by the fact that once they die, they will have to start all over with nothing but 25 points, only enought to buy a hammer but nothing else. These points could have been spent on ammo or nails if the cader got their hammer back wich almost never happens because clueless players loot everything they see. But the problem is that these caders often avoid cading and just go Zmain most of the time wich also affects alot of Bouncers where are usually ment to help new players and teach them the game abit here and there, not to wreck their butts on everymap. (I am not saying any names here and I know its not just Bouncers who do that, its just something I personally see alot of the time. And I can understand that, I for myself often dont want to cade bc of that and because these kleiners dont even repair cades when they have a powersledge/hammer and you tell them to repair and how.

**Comment by CWorm** [comment]
That would indirectly buff humans, besides it would take too much effort just to create such system, I believe that reselling station already stops hoarders from keeping their weapons by giving you chance to get those back for 25% points you spent. Dying should have penalties and I rather keep it that way.
