### ISSUE TITLE
[SUGGESTION] WZS: Increase minimum level to pick up props to level 15 || 20

### ISSUE THREAD

**Issue by jems01** [Azurblau/Zombies.Zone#14]
I think the 'interfering' and 'shitcade' issues are horrible right now. As much as online staff help, there's a limit to how fast you can noodle and nonail someone, which takes time from cading time. It's completely impossible for me to cade if i'm individually nocading people, I have to revert to noodling everyone, then unnoodling players who want to cade.

I think me and many other people in the community have our opinions aligned.

In terms of the issue, 'it prevents people from learning to get better', level 20 isn't hard to get if you stay for a couple of days and grind xp, but this point can also be countered by saying that many shitcaders are over level 20. Personally, through my experience playing on #1 the majority are under level 20, and even if some do interfere/shitcade, there will be a significant lower number of people who do it.

Recently I've never been on without someone over level 20, so I believe there will always be people who can cade.

**Comment by WardenPotato** [comment]
This would have my support.

**Comment by TheFray89** [comment]
exactly what we need. i'm with you.

**Comment by mikan1216** [comment]
I approve

**Comment by Loickun** [comment]
does that also mean that new comers cant nail?

**Comment by jems01** [comment]
no ^

**Comment by Azurblau** [comment]
I've raised it to level 20. Players of lower level can still pick up props if no player higher than level 20 is carrying a hammer.
