### ISSUE TITLE
[SUGGESTION] WZS: Increased repair rate on max health

### ISSUE THREAD

**Issue by HollowZaraki** [Azurblau/Zombies.Zone#140]
Depend repair rate on current health you have, like if you have max health you repair more than if you have 10%

More health = better repair

**Comment by Loickun** [comment]
Why? Whats the reason for that?

**Comment by HollowZaraki** [comment]
so healers also focus on repairers 
healthy repairer = good repair rate
bullied repairer = bad repair rate
that could improve the teamplay mechanic

**Comment by CWorm** [comment]
Humans are strong already, and this would be just a free repair perks for all humans. I don't think they need any more buffs in general.
