### ISSUE TITLE
[SUGGESTION] WZS: MAP PUP

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#141]
I found out that the building itself could have abit more use than we thought about it. 
The roof is totaly empty space, possible to place an attic up there as a sort of last resort for Humans to fall back. Giving them one more room to fall back to. This could be connected with a ladder for example.

What do you guys think?
https://i.gyazo.com/c2b55f5ee8d22c5d2a136c3c61b8691e.jpg

**Comment by jems01** [comment]
@Loickun The title is unclear, are you referring to the map pub?
