### ISSUE TITLE
[BUG] WZS Hardmode: 2nd hand store doesn't give the amount advertised

### ISSUE THREAD

**Issue by HoneyBadger1337** [Azurblau/Zombies.Zone#143]
When selling a gun on the 2nd hand store, it'll give you a price of what you'll recieve, but what you get is less, I caught this happening on #3 but I don't recall seeing it happen on 1 or 2

For example, a gun that might sell for 11 points on the 2nd hand store, only gives you 6 points in actuality

**Comment by CWorm** [comment]
It gives 10% from the sales from the gun, not 20% as intended, though it's hard to determine if we should just fix the display (because there are lots of weapons on the ground if bots are in the game) or fix amount given regardless.

**Comment by CWorm** [comment]
AFAIK this has been fixed couple of days ago, please redo the ticket if it still occurs.
