### ISSUE TITLE
[SUGGESTION] WZS: Overseer chat color

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#154]
I already know someone mentioned something similiar to this in #47 
But the reason why I open this again is because almost everytime I play and try to talk to people or give informations, people dont seem to see or notice my message in chat. 

A command for overseers and higher to temporary have a different chat color would be really handy.
Something like !asay wich enables the color and hilights the text in a color like red or something that is more noticable. It can either last for an entire map or untill you disable it or for only a minute or the message that follows.

I know about Csay but even that wont be noticed sometimes sadly.

**Comment by CWorm** [comment]
Closing, similar reason to #47.
