### ISSUE TITLE
[SUGGESTION] WZS: Nerf Bulldog

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#16]
Bulldog... Please Nerf bulldog...

**Comment by Azurblau** [comment]
Please pick a more accurate title next time. And please provide some details as to why Bulldog is overpowered.

**Comment by Loickun** [comment]
Leave it as it is, its rewarding for what you have to pay for it.

**Comment by jems01** [comment]
I disagree with the comment above. 

In my opinion the bulldog should either be nerfed or it's price upped a lot, WZS is easy enough and we have players who can get the bulldog on round 1-2. This causes a severe disadvantage to early game zombies and can be extremely frustrating.

**Comment by WardenPotato** [comment]
I am in for this. its very annoying and makes being a zombie a very very bad experience if people get a endgame gun at wave 1-2 and ruin the rest of the game

**Comment by Yami07** [comment]
Agreed, Humans being able to get it wave1-2 is aids because zombies wouldnt be able to do anything really.

**Comment by Azurblau** [comment]
Removed the explosion, bullet damage itself is still high though. Waiting for some feedback.
