### ISSUE TITLE
[Suggestion] WZS: Fix ceiling tiles on Rampage

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#160]
Please remove the ceiling tiles in the small room of the map Rampage.
I am talking about the part after you ride an Elevator down, Humans get to cade a small control room, they have around 10 secounds untill Zombie spawn advances and EVEN less time if the zombies destroy the Fence on the upper part of the Elevator too fast.

These ceiling tiles often cause nothing but problems, either they delay the humans by a few secounds or damage humans or even deny the Humans to unphase. Their snap turn is of center wich means you cant even snap turn them quickly in a straigh position.  Nobody ever uses these to cade since they are just too annoying to deal with and often are the reason why humans lose on that part.

**Comment by Loickun** [comment]
Any opinions? Maybe remove tiels and replace them with a pole or two

**Comment by FranceQualityMap** [comment]
Nobody cares about it.

**Comment by jems01** [comment]
Would require a decompile and recompile just to remove something negligible. As I'm responsible for navmeshes and partly for maps I'm going to take the decision to deny it.

**Comment by TheFray89** [comment]
Decompiling the map is not possible since Trazix have made the map Anti-decompiling

**Comment by jems01** [comment]
Update: Tiles are removable via lua, therefore re-open.

**Comment by jems01** [comment]
Recent update made this ticket obsolete.

> - Props that have been picked up and dropped no longer force phase players inside it.
> - Phasing can now be initiated while mid-air, making !stuck pretty much obsolete.
