### ISSUE TITLE
[BUG] WZS: OBJ Hospital

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#161]
Player got somehow stuck under the elevator while all doors where still locked and no power was on.
https://i.gyazo.com/63c9c5ff2ed3881a75d0ad18383df8be.jpg

Amber, MrTrololol and a few others saw it too

**Comment by jems01** [comment]
The screenshot is unclear, the explanation is limited and it requires more clarification. I'm closing because it's invalid. Re-open with clarification and instructions to recreate it if you wish for it to be looked into.
