### ISSUE TITLE
[BUGS] WZS: Fix ZS Maps.

### ISSUE THREAD

**Issue by FranceQualityMap** [Azurblau/Zombies.Zone#170]
**### Ha.. you're got baited.

TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START TRAM IS START** 

-Trazix 2015.

**Comment by TheFray89** [comment]
I like this idea so far i vote 10/10 also TRAM IS START BREAK FOR 35 SECONDS

**Comment by FranceQualityMap** [comment]
I love this idea it's much quality than z.z maps

**Comment by TheFray89** [comment]
z.z need more french quality maps

**Comment by FranceQualityMap** [comment]
TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING TREE IS FLYING

**Comment by TheFray89** [comment]
DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS DONT TAKE MATERIA IF YOU SUCK ASS

**Comment by jems01** [comment]
Please create another ticket? I have no clue what you're trying to get at but I'm closing because it's invalid and trolling.
