### ISSUE TITLE
[SUGGESTION] WZS: a few ideas for zombie vision and loot

### ISSUE THREAD

**Issue by curtiscat2001** [Azurblau/Zombies.Zone#177]
Hey, I have a couple of ideas that I think will make the zombie survival gamemode more fun!

Firstly, there should be drops or loot around the map spawning during waves, encouraging humans to leave there cades and risk searching around for better weapons and ammo, whilst also making zombie gameplay less repetitive. As they are currently just throwing themselves at cades for 6 rounds. The next bit will make this more balanced for the humans

I think the whole zombie vision, where the zombies can see players through walls could be changed. Instead of seeing players through walls the zombies could have a "smell meter" that get higher when they are near a human.

I think this would be good because it allows humans to hide without putting themselves behind cades, therefore they would be able to wander around the map and collect items, and add a bit of tension whilst they hide from the zombies and sneak there way back to safety as zombies hunt for their prey. This could also open doors for new zombie types prehaps, and also things such as camouflage and smell dampeners on humans.

**Comment by jems01** [comment]
Great ideas but each suggestion needs their own thread.

Please create more tickets accordingly.
