### ISSUE TITLE
[SUGGESTION] WZS: Buff Quasar PLEASE

### ISSUE THREAD

**Issue by Aquid0** [Azurblau/Zombies.Zone#18]
**Why you should Buff Quasar**
It literally does 15 damage per shot for me even with apricot sniper, the slow is not even noticeable also. The reload takes about 5 minutes and I can't even get to full mag on an obj without dying from zombies behind me, and it also costs about 200 points.

**Why you shouldn't use Quasar and buy another gun** 
You can LITERALLY buy Twin peashooters and you can get more profit and more total damage in a wave, whereas you will get a maximum of 3000 damage, even if you use aimbot, in 3 waves.

**The End**
Please, I swear to god, remove this weapon or buff it so it can have a chance against some of the high tier guns

**Comment by Azurblau** [comment]
Decreased the price from 235 to 175. I won't change stats on quasar though as it is a very good runner weapon, rivalling with Poacher.
