### ISSUE TITLE
[BUG] WZS: Charger zombies cause leg damage

### ISSUE THREAD

**Issue by jems01** [Azurblau/Zombies.Zone#2]
Causes big slowdown for players hit by chargers, pretty much instakilling runners.

**Comment by Azurblau** [comment]
Might be fixed, I didn't have the opportunity to test it yet.

**Comment by Azurblau** [comment]
Instead of fixing slowdown which is a feature affecting all damage by zombies I've nerfed charger damage against humans by 50% now. Damage against cades is still the same as before.
