### ISSUE TITLE
[SUGGESTION] WZS: Add Bosses On Objective Maps 

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#25]
Adding bosses in an Objective Map. it would also give more difficulty to the gameplay (since its extremely easy for humans to win any map), Now I'll give you an example: every 6-7 minutes (based on the map and its size) will spawn a completely random zombie boss from this one: 
- Tickle Monster.
- Nightmare.
- Bonemesh.
Yes, also depends on the number of active players: 30 players is ok to activate this mechanism also to balance the zombies (since they are EXTREMELY disadvantaged under every point of view.)

**Comment by Loickun** [comment]
I disagree over 20.000 Kleiner's have been hurt during the Movie.
Other words: Its already difficult when you have not a good team.
Allthough I think shade could be a usefull boss too...

**Comment by jems01** [comment]
Quoted from your previous post:

> Concerning bosses for obj maps, I discussed this with Jack and we reached the conclusion that bosses such as the shade would be completely overpowered (as most obj maps don't have many cades), instead, we combated this issue by using a human dmg coefficient. Suggestions for the multiplier are welcome, and of course, mention the map. 
> 

It's unlikely that we'll see bosses on objective maps in the foreseeable future, objective maps are hard enough already and balancing scripts like the one seen on rampage shouldn't be ruled out for other objective maps, if that's to make them easier, or harder.

**Comment by TheFray89** [comment]
understandable, but I dont think absolutely that its an idea to discard, it is simply one more way to give interest to the maps since 90% of the players vote an obj map only to farm points.
