### ISSUE TITLE
[SUGGESTION] WZS: Add Votekick Command for Bouncers

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#26]
Add the command "votekick" for bouncers, because unfortunately, they will never solve the problem of people who troll on purpose.

**Comment by Loickun** [comment]
I agree

**Comment by BrandonZFong** [comment]
I agree with this

**Comment by jems01** [comment]
Unfortunately I'm at fault here since I forgot to remind him about it last weekend.

It's likely that bouncers will get this in the near future

**Comment by TheFray89** [comment]
Nice to hear that! and dont worry, that happens to forgot something

**Comment by Loickun** [comment]
Great to hear we can do something against trolls/griefer in near future
