### ISSUE TITLE
[SUGGESTION] WZS: New Voting System for Maps

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#27]
If a map is chosen and played (example Chaste), this one cannot be chosen for the next 10 maps (8 for the obj, since we have only 5 Objective Maps available). this also to give space to the maps that have not yet been played, so as not to make things monotonous and too repetitive.

**Comment by Azurblau** [comment]
This is already in place. The votemap shows all maps that are voteable except those still in cooldown. Default is 5 rounds cooldown, individual maps might have manually adjusted cooldowns.

**Comment by Azurblau** [comment]
If you want the cooldown to be increased or a different feature, open another ticket.

**Comment by TheFray89** [comment]
sure!
