### ISSUE TITLE
[BUG] WZS: PukePus Code Issue 

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#28]
Sadly when you are going to use Pukepus, mostly of the time when you kill a human it appears that:

"projectile_poisonpuke"
![20180210134609_1](https://user-images.githubusercontent.com/35899421/36086537-b6db2fd8-0fd5-11e8-9133-e00a2c1e6a01.jpg) instead of this ![20180210134622_1](https://user-images.githubusercontent.com/35899421/36086548-c7c13202-0fd5-11e8-8df7-ad047435d9ea.jpg)
I've got to test this problem, and unfortunally that happens 3/4 of the times. i hope that will be fixed soon as possible.

**Comment by WardenPotato** [comment]
Ive researched this a bit and its not in pukepuss its code, the issue is somewhere else. this may be a very demanding ticket
