### ISSUE TITLE
[SUGGESTION] WZS: Remove DetPack from EVERY Objective Map

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#29]
currently people who play every kind of obj map only play it only for bombard the map with these Incredibly unbalanced detpack and make extremely easy points without any difficulty, but especially to make the zombie experience frustrating, boring, and repetitive, Since the only thing you are doing is Exploding and dieng without stopping.
This is the result of what I mean:
![20180214202811_1](https://user-images.githubusercontent.com/35899421/36291169-0f61aa5c-12d2-11e8-8454-34ed70e23aa6.jpg)
Seriously? 
almost 700 Points of ONLY Detpack without using other guns... Is that balanced? 
![20180214202812_1](https://user-images.githubusercontent.com/35899421/36291201-3b38ea6e-12d2-11e8-8fa0-7ae073416616.jpg)
![20180214202816_1](https://user-images.githubusercontent.com/35899421/36291203-3edb2060-12d2-11e8-8847-874ff5d10f9e.jpg)
It's not fun to see people Who Leave the server because it's impossible to react of this detpacks.

Please... PLEASE, REMOVE the detpack from Every obj map Especially Vertigo Ed Enervation (People vote these two maps just to farm points no stop..)
This change would make an huge Impact to the gameplay in all the obj maps.

**Comment by jems01** [comment]
I would support a method preventing detpacks being used on obj maps.

There is already a lock for certain bosses on (exclusive) maps which works very well.

**Comment by TheFray89** [comment]
Thats great to know!

**Comment by BrandonZFong** [comment]
I don't know what the detpack look like, but is it overpowered weapon?

**Comment by TheFray89** [comment]
C4

**Comment by Azurblau** [comment]
I've added a cooldown of 60s between placing detpacks on every map. If that doesn't solve the issue please comment.

**Comment by Azurblau** [comment]
Decreased cooldown to 30 seconds and cooldown resets if the detpack has been detonated. This should prevent stacking.

**Comment by TheFray89** [comment]
Thank you a lot Jack <3
