### ISSUE TITLE
[SUGGESTION] WZS: Healing grenade change

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#30]
What if we change the Healing Grenade to a somesort of a Torch/Spike you have to deploy by throwing it in the ground so it doesnt roll away or glitch under the map when props are bouncy like that one time. (Deploying would be a cool idea but that defeats the purpose of a quick way to heal) Sorry I dont mean to spam here tho. (Besides its a one time use only)

What do you think?

**Comment by Loickun** [comment]
Or give it a bigger radius of Healing

**Comment by Azurblau** [comment]
Range is doubled now.
