### ISSUE TITLE
[SUGGESTION] WZS: New Zombie Class "The Medical Zombie" 

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#32]
Very similar to the normal one can attack like a normal zombie but with the difference that it can heal the other zombies with gibs by clicking with the right mouse button.
The medical zombie can create 1 gib every 4 seconds, and every gib can give from 8hp to 10hp.
Stats:
- Walk Speed= 175 (More faster Than the normal Zombie)
- HP= 180 (Since he can heal, his hp are reduced.)
- Range= 48 (Same of Normal Zombie) 
- Damage= 25-30 (is intended to be a Normal Dps)
- Damage For Second= 20
- Can be unlocked in Wave 3.
- Width= 1.5 (Exactly the same of Normal Zombie)
- Delay= 1.2 (Normal)
- Appearance= Visibly its similar to the normal zombie, with the only difference that will wear a Medic's backpack and with clothes also similar to a medic (like the medic on Half Life 2)
![medic](https://user-images.githubusercontent.com/35899421/36345933-3948fb60-143d-11e8-845b-9b2f062920d1.PNG)

My personal Opinion: This could really make a great contribution to the zombies, but above all, could make sure you can have more teamwork when you are a zombie and give a lot of changes in game.

**Comment by CWorm** [comment]
The boss - Sphynx - already exists and fills that role, having common zombies being able to use healers sounds like a bad idea.
