### ISSUE TITLE
[SUGGESTION] WZS: Add a Command To Show the MapStats

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#33]
Basically that will count how many times a certain map has been played and won.
i was thinking about something like: !maprate or !mapstats but doesnt matter what exaclty of them.

This is an example who i made: 
- This Map Has Been Won 3% of the Time And Played 120 Times.

Thats will be extremely interesting for the following reasons:
- If a map has been won a few times it will give you much more satisfaction to win it.
- To see if a certain map need to be balanced. 
- See which map is Easy and which map is Hard.
- To know how often a certain map is played. (Overplayed or the opposite)

**Comment by UrNibba** [comment]
+1 nice idea
