### ISSUE TITLE
[SUGGESTION] WZS: Boss Selection Based on Wave Damage Instead of Total

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#34]
I was thinking about it so boss selection occurs based on the total damage (barricade and human) per wave instead of the total damage for the game. Reasons for doing this would be:

- Makes it impossible to secure a boss and then go AFK. You still have to “compete” with other players for boss to get it again next wave. If you’ve done nothing all wave and then suicide you won’t get boss instead of it being high chance that you’ll get again from your previous total damage.
- Spices up the same player getting boss, hopefully, and encourages zombies to not “give up” on getting boss and encourages them to be aggressive all game. It would reward skill more actively.
- People would have much less excuse to complain about bad players who get boss zombie, since with this they should just try harder to get it within the wave they’re currently in.
- Redeeming and suiciding to become boss again. Seems completely bizarre that this can be a thing. If you just want to play zombie then turn off redeems.

**Comment by Azurblau** [comment]
Sounds like a simple reset of accumalated damage just after a boss spawned would do the trick. I might also look into making damage done as boss count less or not at all to avoid the suicide respawn trick.

**Comment by Loickun** [comment]
I agree, that is something we deffinitly need. How many times have you tried so hard to become the boss and at the end someone else gets it because he/she dealed more damage in total but was last round AFK.

**Comment by Fume09** [comment]
+1

**Comment by Loickun** [comment]
+1 Please fix.<3
