### ISSUE TITLE
[SUGGESTION] WZS: New Energy/Pulse Gun: "Gluon" Laser Beam

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#36]
I think it's time for pulse weapons to get a little twist

Suggestion Stats:
- Ammo Per Shot= 1
- Price= 475 
- Price at Intermission= 380
- Profits= 0.89
- Damage= 38
- Damage Per Second= 570
- Clip Size= 100 
- No Reload (Exactly Like Terminator and Vulcan) 
- Held Walk Speed= -35%
- The Weapon will overheat after about 6-7 seconds and it will cool after 4-5 seconds
- Top Tier Pulse  Gun
- No Recoil

Particularity of this weapon: 
- It will have a penetrating damage that can slow down the zombies in its radius
- Thanks to the fact that it will overheat every 6 seconds, it will avoid being an unbalanced gun

Aspect:
![gluon](https://user-images.githubusercontent.com/35899421/36481496-ac9f586a-1718-11e8-9556-fa786baadcc0.jpg)

Obviously they are statistics that you can change, the ones I have just listed are only suggestions stats.

**Comment by Yami07** [comment]
Really like the idea,but i would perfer a higher clip size since your paying for something that is going to do a shit ton of damage why not make it so you can have more ammo in the weapon

**Comment by Fume09** [comment]
I Love this idea, but Fray, like yami said, this gun is going to do a tons of damage.
Maybe  you have to change something for this weapon.

**Comment by CWorm** [comment]
I don't want to redo content from other servers. Please give out original ideas, not copies from another server, thank you.
