### ISSUE TITLE
[SUGGESTION] WZS: Weapon - Health Storm

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#37]
[HEALTH STORM](https://i.gyazo.com/d14734cab852ea46dfbcf6a9091bdafb.png)

Weapon type: Healing beam rifle/ Flamethrower.
It should be around 220 points and it works like a flamethrower, healing humans fast but consumes lots of ammonition there for.

**Comment by CWorm** [comment]
'Guardian' already fills that role.
