### ISSUE TITLE
[SUGGESTION] WZS: New Boss: "Reaper" Zombie Boss

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#38]
It’s a boss zombie with moderate health that uses a tongue / detachable claw of some sort to drag humans to itself. 
It deals moderate damage on attack (no more than a normal zombie) but has a permanent poison cloud aura that damages and slows humans that are very close to it (it’s kind of like the zombie spawn gases). 
The point of this boss zombie is to pick off loners and humans that are outside of barricades. 
Most of the other boss zombies specialize in attacking barricades so this boss would fill in that gap.

**Comment by CWorm** [comment]
Entity already fills that role.
