### ISSUE TITLE
[SUGGESTION] WZS: Improve zombie hp health or nerf some of the weapons

### ISSUE THREAD

**Issue by Yami07** [Azurblau/Zombies.Zone#4]
Improve zombie health , as you can already tell the weapons on wzs are extremely overpowered sometimes leaving zombie wins at ending rounds. 
Earlier waves zombies can barely do anything at all thats why im saying to improve the health or nerf some of the weapons, doing this could bring a more balanced gameplay.At this point most players try to get kills to turn into a  boss since they have more hp and can do a shit ton of damage.

**Comment by CWorm** [comment]
Please be more specific as which weapons you think are overpowered or how zombie health should be improved, the idea is too broad

**Comment by Azurblau** [comment]
WZS is designed to be a casual gamemode with an exponential difficulty rise in a round. Only wave 6 (and maybe 4 and 5) are designed to be challenging while previous waves provide some time to grind for better weapons. For pure challenge, try hard mode.
If despite that there is indeed something that could be improved balance-wise, please create a more specific ticket.
