### ISSUE TITLE
[SUGGESTION] WZS: Add "Prop Destruction" To the list of things Logs/Console Records

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#40]
Example: 02/18/12 04:14:02 <STEAM_0:1:14034114> Bob destroyed prop props_junk\wood_crate002a.mdl

Just in case if I/someone needs to report someone breaking props and griefing related to it in general.

**Comment by Loickun** [comment]
+1  Argreed

**Comment by jems01** [comment]
+1

**Comment by Azurblau** [comment]
Already exists, check the "Break" log type. :+1:
