### ISSUE TITLE
[SUGGESTION] WZS: Map vote changes

### ISSUE THREAD

**Issue by Kowoalski** [Azurblau/Zombies.Zone#42]
I would like to suggest that the map pool during the map votes was reduced to roughly around 10 maps, and make the displayed options the least played maps, ones that hadn't been touched in the last 5-10 matches or so.

Separate suggestion: Could the cooldown on objective maps be increased to 2 or 3 maps before a new objective one has to be picked? With how small the obj map pool is, they get repetitive very quickly.

**Comment by TheFray89** [comment]
I have already talked about this topic.

**Comment by Azurblau** [comment]
"Separate suggestion: Could the cooldown on objective maps be increased to 2 or 3 maps before a new objective one has to be picked? With how small the obj map pool is, they get repetitive very quickly."
Please open that as its own ticket. This hasn't been discussed yet.
