### ISSUE TITLE
[SUGGESTION] WZS: Upcoming changes list

### ISSUE THREAD

**Issue by Kowoalski** [Azurblau/Zombies.Zone#43]
Could we get a list on the discord going that would consist of upcoming changes/tweaks/additions/removals to the server in the near future? Would help in preventing multiple suggestions of the same nature, or suggestions that were already approved

**Comment by jems01** [comment]
I understand the point of a 'coming soon' list, but the points you provided can easily be solved by just reading through github closed and open issues.

**Comment by Azurblau** [comment]
Chances that a major WIP gets its user-submitted ticket during unannounced development is quite low. Minor chances like balance tweaks don't take much time either. It is a good idea but not worth the effort yet.
As for avoiding duplicates, your best bet is to read through the github issues. It is still overviewable as of now and even if something slips through, no biggie, a moderator just closes it labelled as duplicate as done in any major github project.
