### ISSUE TITLE
[SUGGESTION] WZS: Disable Milk on Vertigo

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#44]
More and more people try it out and more people abuse the exploid of it.
Maybe ban the item from the map like we did the Concrete Barricade on others, or is that not possible?
or make the Area down there to an insta triggerkill zone on touch?

**Comment by TheFray89** [comment]
Banning the refrigerator directly would be a great idea, but loic, you have to know that vertigo itself have a ramp that you can reach even without milk(i spectated many people who jump and survive at this ramp). so basically there isnt a way to avoid that properly.

**Comment by Loickun** [comment]
Cant we create a Trigger zone after the first elevator part out there?

**Comment by TheFray89** [comment]
This is up to admins or the mapper itself

**Comment by jems01** [comment]
I will patch the roof with invisible static props when I have time. Banning milk is possible but It will be ineffective if you can pick it up.

**Comment by Azurblau** [comment]
I've removed the milk from the fridge for vertigo. It's still obtainable in other maps. As for the ramp, I'll leave that to @jems01 to fix. He will close the issue then.

**Comment by jems01** [comment]
I've now patched the roof so it shouldn't be possible to jump off the side.

If there's any spots I've missed please message here or on Discord

Closing ticket.
