### ISSUE TITLE
[SUGGESTION] WZS: Adding a timer to the dizziness/drunk effect

### ISSUE THREAD

**Issue by TriangularUnion** [Azurblau/Zombies.Zone#45]
Is it possible to ad a timer to the drunk/dizzy effect of beer and  sphynx like there is for poison and ghouls touch ?

I (and sone other people) think this would help players.

**Comment by jems01** [comment]
Do you mean concerning how long the effect lasts?

**Comment by TriangularUnion** [comment]
yes

2018-02-28 11:58 GMT+01:00 jems01 <notifications@github.com>:

**Comment by WardenPotato** [comment]
This could work +1
