### ISSUE TITLE
[SUGGESTION] Custom color chat for overseer+

### ISSUE THREAD

**Issue by Yami07** [Azurblau/Zombies.Zone#47]
This could work to tell a difference between overseer and bouncers and regular members, would make it look better since overseers are higher staff than bouncer and member. 
Plus this would also give you a nice feel to typing with your own set color ;)

**Comment by Loickun** [comment]
Interesting indeed but not sure if its necessary

**Comment by jems01** [comment]
Not necessary but would be nice for aesthetics.

**Comment by Fume09** [comment]
its not useless, and not useful.
it's a middle way

**Comment by Loickun** [comment]
I'd say why the heck not.

**Comment by WardenPotato** [comment]
Why not
