### ISSUE TITLE
[SUGGESTION] WZS: Overseer !pack command

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#48]
Make wooden planks from the agnis-kit packable with !pack.

I'v had it yesterday that I couldn't cade because someone was blocking the  door with 2 of those boards and you could crouch walkk through it so it wasn't even a cade.
I could have kicked him but that seemed like not reasonable.
I was trying 10 minutes long to get that player to move his planks.

Note those planks where behind me covering the door way and proventing me to get doors in the main room. I took those screenshots right befor I went Zmain.

In order:
https://i.gyazo.com/25ffefc3ca38a78e3c106590228fc169.jpg
https://i.gyazo.com/ba950f7a90beb4952d14133a2d4692f0.jpg
https://i.gyazo.com/6d8c0d9ba14faa4307be9e5ed1d9ff4b.jpg
https://i.gyazo.com/cee12f235ba338a729ad0fb7b75c2b3c.jpg
https://i.gyazo.com/c17cd2b7a056994d9df09527bf1d7a66.jpg

**Comment by jems01** [comment]
You're in your power to kick him after warnings.
