### ISSUE TITLE
[SUGGESTION] Balance Hoomans and Zombies

### ISSUE THREAD

**Issue by HollowZaraki** [Azurblau/Zombies.Zone#49]
limit speed traits
limit purifier to 1 (only one active at the same time)
there should be more than 1 boss at the same time if many players are online
Bots should be able to get boss when no human is zombie
and also prevent human from spawn camping after wave 2 or 3
Limit strong weapons like anti material sniper, punisher shotgun, caws and so on.
Weapons that are game changing like doing a lot of dmg or causing aoe dmg(maybe readd then bulldog with a limit of 1).
And also it would be increasing the use of different weapons because the fave weapons is already in use

**Comment by WardenPotato** [comment]
+1

**Comment by Loickun** [comment]
+1

**Comment by Yami07** [comment]
+1, if weapons are being nerfed I think this would Definietly make things more fair .

**Comment by CWorm** [comment]
Too broad, please explain "limit strong weapons (since humans get stronger and stronger but zombies always stay the same)" - it's unclear which weapons are strong or just overused.

**Comment by jems01** [comment]
Separate suggestions should be open in separate threads, closing.
