### ISSUE TITLE
[BUG & SUGGESTIONS] WZS: Suggestion and some fix issues

### ISSUE THREAD

**Issue by v1red** [Azurblau/Zombies.Zone#5]
Hi lads I have a few sugestions and few issues. Is it possible to change the boss selection when are more than 10 players on. I belive now its 5+ but when its like 10 usualy 2 3 go z main and u have almos no chance of wining. Aswell the anti-return trait steroids witch soupose to give u muscular trait dosent work, you wont be able to lift heavy props. and after death you u reedem the speed traits not working anymore. And if possible the gas mask to work same as resistant traint to take no damage from poison, at the moment it works only against sfinx and still get damage from vestigant poison gas from z spawns and poison headcrab.

**Comment by Azurblau** [comment]
Please create separate tickets for separate issues. Thanks.
