### ISSUE TITLE
[SUGGESTION] WZS: Introduce a limit to Aderrall

### ISSUE THREAD

**Issue by WardenPotato** [Azurblau/Zombies.Zone#51]
There should be a limit on aderrall to prevent people abusing it and for example outrunning screamers. it happens multiple times a day and is just disruptive to the game. I suggest it will be incrementally priced (first buy 100, second 200, 400, etc or +100 each time) or/and there is a hard limit on about 311(Open for debate) speed

**Comment by Loickun** [comment]
+1 really annoying when a human on with +xxxx speed melees you as boss and u cant do anything against it

**Comment by TheFray89** [comment]
*cough* *cough* Fray *cough*

**Comment by Yami07** [comment]
+1 would love a limit

**Comment by TheFray89** [comment]
+1 
a limit will be really awesome in my opinion, and i'm a runner 3/4 of the times

**Comment by mikan1216** [comment]
+1
Good :)

**Comment by Azurblau** [comment]
Adderall now has a diminishing return of 75%, means it flattens off to a maximum of slightly below +30 (first purchase = +7, third purchase = +7 * 75% * 75%, etc).
