### ISSUE TITLE
[SUGGESTION] WZS: BOSS REWORK PLEASE

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#53]
For the love of god, rework the Boss system. I'v litterly killed 4 Humans as a Zombie in wave one and was the pretty much the only player with Kills on the Zombie team. But for some wierd stupid reason the Game thought "lets just choose this random AFK player who hasn't done what so ever".

It picked a Player that only damaged props across the map. While others where trying to kill Humans.
And this is just one example, stuff like this happens alot and alot of Bosses get wasted because of that. 
It would also make human players more carefull since there could be 4 to 6 Boss Zombies outside if they managed to stay alive their waves.

Please make it Damage dealt per Wave not total Damage.
Its litterly the worst when you try your best and then have to watch how 2 Bosses get wasted because of some random player who for some reason dosent want to attack the Cade.

**Comment by Azurblau** [comment]
see #34
