### ISSUE TITLE
[SUGGESTION] WZS: Buff Vindicator 5.56 Gun

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#54]
Paying 400 points for a gun who have bad fire rate and bad profits isnt really an awesome thing.
i suggest to increase the fire rate more when you are shooting with it, because at the moment is an extremely horrible gun.

**Comment by v1red** [comment]
+1

**Comment by CWorm** [comment]
Increased firerate and turrets fire the gun with maximum 'heat', will close this in a week, waiting for more opinions.

**Comment by CWorm** [comment]
Works fine.
