### ISSUE TITLE
[Suggestion] WZS: Level rewards

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#55]
Maybe add the reward for players with a certain level get a few more points to spend in the prepare phase. Like u reach lvl 80 and get +5 points or something like that.

**Comment by UrNibba** [comment]
+1

**Comment by Yami07** [comment]
+1

**Comment by v1red** [comment]
+1

**Comment by jems01** [comment]
I'm heavily against this idea, players who are higher level already get passive rewards such as +5%hp, this would make the game easier for veterans, causing a severe disadvantage for new and low level players.

**Comment by TheFray89** [comment]
in my opinion the perks are enough, because in this way people with highest level are extremely advantaged.

**Comment by WardenPotato** [comment]
-1 High levels player do not need more points

**Comment by CWorm** [comment]
I'll increase level rewards ceiling instead of boosting what already is in.
