### ISSUE TITLE
[SUGGESTION] WZS: Some way to fix the "joined too late couldn't buy anything" issue (maybe autobuy).

### ISSUE THREAD

**Issue by Azurblau** [Azurblau/Zombies.Zone#56]
An idea would be to make a list of stuff to be bought with specific ranges of leftover points. E.g. someone has 50 points left? Buy him a glock and some ammo.

If you have other ideas, please comment.

**Comment by TheFray89** [comment]
actually since when late joiners get 100 points is fine, problems come when a person forgets to buy weapons from the worth menu

**Comment by jems01** [comment]
No, people who join after wave 1 has started will receive 100 points, but if you join with about 10 seconds left, this problem becomes apparent.

How about the game autobuys a random class?

**Comment by TheFray89** [comment]
oh nvm, you are right jem, and i think an autobuy random class will be extremely awesome to solve this issue

**Comment by Azurblau** [comment]
Players are now given dual glocks or dual owens and as much pistol ammo as the remaining points allow.

**Comment by Azurblau** [comment]
I don't think this niche problem requires a more complex solution. If you do think that, please open another ticket.
