### ISSUE TITLE
[SUGGESTION] WZS: Additional Nails Type

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#58]
It would be really interesting to see something like:

-Barbed Nail:-

- Cost: 4 Points (each nail)
- Ability: Causes Zombie to take damage from attacking props but it will reduce prop health

-Steel Nail:-

- Cost: 7 Points (each nail)
- Ability: prop repair increased by 15% 

-Heavy Nail:-

- Cost: 8 Points (each nail) 
- Ability: Increase Prop HP By 20%

**Comment by Fume09** [comment]
Why not? :+1:

**Comment by jems01** [comment]
I like the idea but the prices would have to go up a lot, as humans are already very powerful.

**Comment by TheFray89** [comment]
Thats true jems, any suggestion for the price?

**Comment by Yami07** [comment]
Agreed!!

**Comment by Azurblau** [comment]
Good idea, but requires some time to implement. Low priority for me.

**Comment by WardenPotato** [comment]
I agree with the higher price of jems. Great idea +1
