### ISSUE TITLE
[SUGGESTION] WZS: New Cading System

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#60]
let's make an example with a chair:

The Standard Health is 424 hp, so what will happen now with this new mechanism? is based on the amount of nails that you add to a certain prop.

- 1 Nail = No change, the prop still with his normal Hp.
- 2 Nails = It will increase the prop hp by 75  so now the prop will be 499 Hp+ Avoid prop kills. 
- From 3 to 4 Nails = It will increase the prop Hp by 75 hp. 

The maximum amount of nails that you can add is 4

So:

- with 1 nail= 424 hp
- with 2 nails = 499 hp
- with 3 nails = 574 hp
- with 4 nails = 649 hp

This mechanic can be used for all props, but it will never increase the hp more than 75.

**Comment by Yami07** [comment]
+1

**Comment by Loickun** [comment]
+1

**Comment by Azurblau** [comment]
If any, I'd reduce the first nail's health to half (x0.5) the original health while the fourth nail increases it to x1.5 of original health, each nail being an extra x0.25 of original health. But I'm not sure if we should increase cade healths in the first place.

**Comment by WardenPotato** [comment]
We should definitely not increase cade health above what it currently is
