### ISSUE TITLE
[SUGGESTION] WZS: Healing Station 

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#61]
- Costs = 200
- spreads a healing fog/aura that heals continuely the humans by a little amount (1-3 hp idk)
- needs heal ammo to spread the fog
- should consume the ammo either by every  minute/second(by time) or if the fog/aura heals someone
- should be a deployable (affected by enterpreteur)
- Packable
- Ammo Capacity 500 Maybe 600
- if a player were to fill your medical station with medical ammunition he will receive 1 point for each time he adds it

**Comment by CWorm** [comment]
Too overpowered, self-healing is already a huge problem in WZS, there is no need for more unrestricted healing.
