### ISSUE TITLE
[SUGGESTION] WZS: Re-Add Obj Tag 

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#62]
Currently the obj maps seem completely non-existent, in about 3 days (I'M NOT JOKING) I havent seen or played a single map, and I repeat IN 3 DAYS!
from overvoting to completely kill obj maps is an huge difference..
especially when people want to play an obj map but they dont even know where its and when you realize where is the map is too later, because when you close the mapvote you cant open it anymore for a possible re-vote. everything is extremely frustrating and annoying in this way from every point of view and i really hope the obj tag will come back but with a small mechanic change for obj appears on rotation.
and yeah, if you are wondering what the community thinks of this change, I can tell you that they literally detest this change because they find it "Completely useless and Extremely Frustrating" because you can't go crazy to look for a single map you want to play after you havent played it for a while.

**Comment by Azurblau** [comment]
I won't add a simple [OBJ] tag back as it garners too much attention to these maps in particular. If any, I'd introduce "map type icons", an icon for hallway maps like chaste/shithole, an icon for large maps like scrapmetal, for sniping maps like MLT defense, etc. That way obj-maps should blend in nicely and not appear as a blatant "vote me" map.

**Comment by CWorm** [comment]
OBJ tags already exist in map name underneath general name, I don't think it's necessary anymore.
