### ISSUE TITLE
[SUGGESTION] WZS: Rebalancing For Butcher

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#64]
The Old Status of The Butcher was:

- Health: 900
- Speed: 275
- Damage: 30 
- Swing Delay: 0.4
- Range: 66

Well, basically you notice that there is a great imbalance as far as damage and speed are concerned, so this is what I suggest:
New Status For The Butcher:

- Health: 850
- Speed: 250
- Damage: 22
- Swing Delay: The same 
- Range 60

this in my opinion, will make sure that the butcher does not become a destructive machine of humans. Then since humans are extremely advantaged will be not really hard to kill him and it would really be interesting to see butcher back with this stats.
Please if you have a stats that you want suggest or you like this one feel free to comment.

**Comment by Azurblau** [comment]
The issue with butcher is that it kills before you or your team notices it. It need to have much more health in exchange for lower damage so that there is more time to react to butcher as a team. Ideas to make butcher more obvious are welcome.

**Comment by v1red** [comment]
Im pro. Dont know why was removed first place. It was always easy to kill. Especially with rifles one head shoot was insta kill.

**Comment by WardenPotato** [comment]
You could introduce a growl on the first swing a butcher makes to announce his presence. +1

**Comment by Yami07** [comment]
+1 sounds good to have it back

**Comment by Azurblau** [comment]
Even though this ticket is the original, please continue discussing it there: #79
