### ISSUE TITLE
[SUGGESTION] WZS: Increase the amount of Beacons Placeable 

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#66]
Increase it from 3 to 4 so that can be perfect for deployables, since them are 4

**Comment by Azurblau** [comment]
They're designed for informing players about stuff. The reason for the limit is to reduce the noise of beacon overuse. A better idea might be to have the default beacon not be visible at all, forcing players to actually pick a message, only then increasing the limit doesn't affect the noise much.
