### ISSUE TITLE
[SUGGESTION] WZS: Prevent mall overpicking

### ISSUE THREAD

**Issue by WardenPotato** [Azurblau/Zombies.Zone#67]
To prevent the amount of overpicking of mall. Prevent the ability to choose ZZ4 after V8 has been plated and V8 after ZZ4 has been played, its the main cause of many complaints

**Comment by TheFray89** [comment]
i completely agree with that. 
Is annoying and most of the people ragequit when thats happen

**Comment by Azurblau** [comment]
I added a feature that allows maps to be "cooldown-linked", as in, one map gets voted, the other also gets the cooldown. This has been configured for the mall maps now.
