### ISSUE TITLE
[BUG] Placing Turret Frame removes ammo from invenrtory

### ISSUE THREAD

**Issue by h4uja2** [Azurblau/Zombies.Zone#68]
### Description of the Issue
Had 200 smg ammo, put sentry, ammo has dissapeared

### Steps to Reproduce the Issue
1.  Buy 200 smg ammo
2.  Buy Turret Frame
3.  Put Turret Frame on ground
4. Check your smg ammo

### Expected Behavior
I do not lose ammo when placing sentry frame

### Actual Behavior
I lose ammo when placing sentry frame

**Comment by UrNibba** [comment]
had a same issue +1

**Comment by h4uja2** [comment]
Before placing turret: https://i.imgur.com/vXjgD7Q.jpg (look at ammo)
After placing turret: https://i.imgur.com/rjztC4h.jpg
