### ISSUE TITLE
[SUGGESTION] WZS: New Hammer Model

### ISSUE THREAD

**Issue by TheFray89** [Azurblau/Zombies.Zone#77]
This is a Re-Make of the old Hammer and the Electrohammer models and include:

- New Animations
- C_hands

 Normal Hammer 
![20180322203130_1](https://user-images.githubusercontent.com/35899421/37793206-9a109c3a-2e16-11e8-8d0e-cc9f296788be.jpg)

 ElectroHammer
![20180322203125_1](https://user-images.githubusercontent.com/35899421/37793260-c8993242-2e16-11e8-904d-3ecb014a90b1.jpg)

A video who can show the Hammers in action (Thanks to Warden Potato) 
https://www.youtube.com/watch?v=TKkYc6MJPUw

- Code
-[Hammer Model by TheFray and How Super Terrible.zip.zip](https://github.com/Azurblau/Zombies.Zone/files/1916745/hammer.zip)
-[Electrohammer Model by TheFray and How Super Terrible.zip](https://github.com/Azurblau/Zombies.Zone/files/1840142/weapon_zs_electrohammer.zip)

I hope you will accept our work, and Special Thanks to "How Super Terrible?" for having helped me out with this small project. 
we have put my heart and soul to do it :) 
- How Super Terrible? http://steamcommunity.com/profiles/76561198319479102/

**Comment by Azurblau** [comment]
It seems to be missing the models.

**Comment by TheFray89** [comment]
The server runs with a github version or the workshop version of zombie survival?

**Comment by TheFray89** [comment]
and what you mean with missing models? explain better please

**Comment by TheFray89** [comment]
done, thank you for reporting the problem.
