### ISSUE TITLE
[SUGGESTION] Knife

### ISSUE THREAD

**Issue by v1red** [Azurblau/Zombies.Zone#80]
If you join server 1st round you will se 80% of players dropping the knife and the rest 20% will not use it. Damage its low, points terrible, and my sugestion will to remove it sience I havent see any player actualy using it or improve it double points, more damage or fell free to add something to make it worth and beeing used more

**Comment by Azurblau** [comment]
It's free. I myself happen to use it to get the last few points for a new weapon when out of ammo. I could replace fists with the knife, but I'm not sure removing the knife or making the free knife opt-in is a good idea.

**Comment by Azurblau** [comment]
See #119. Knifes are sellable now.
