### ISSUE TITLE
[SUGGESTION] "zs_disabledetailsonlowfps 1" should re-enable disabled models after round

### ISSUE THREAD

**Issue by h4uja2** [Azurblau/Zombies.Zone#81]
> "Low framerate detected. Disabling some rendering features for **this round...**"

But it never re-enables those rendering features.

If it works as intended then change the chat message and make "zs_disabledetailsonlowfps 0" re-enable what it has disabled.

Also while we are at it - add this setting to F4 GUI.

**Comment by Azurblau** [comment]
It re-enables fine for me. Are you sure you mean round (from start to map change), not wave (between intermissions)?

The other suggestions are good. Ticket stays open.

**Comment by h4uja2** [comment]
Yep, I confused round and wave.
