### ISSUE TITLE
[SUGGESTION] WZS: deployables

### ISSUE THREAD

**Issue by Mauro-the-Wizard** [Azurblau/Zombies.Zone#82]
Does it makes sense that when you press on armory bench and you don't receive armor because its full, but the problem with fridge is that you won't receive food because you have it all, but fridge makes that like you took food and there is this message: "~you have all food, eat something first" so you need to wait another 100 seconds because you've pressed on it but you picked up nothing. And about resupply box I have just tested out that I had only one gun (I had baikal but its same with any gun) and I switched on knife and used resupply and I haven't got anything. 
Please fix at least one thing that I have mentioned from above.

**Comment by Loickun** [comment]
That you dont get ammo when you dont hold a weapon is normal. It's been like this for ages.
It happens to me sometimes too but giving you ammo when you dont hold a weapon would be the resuppply would have to give you every ammo type wich would be OP.

**Comment by CWorm** [comment]
The resupply box gives you SMG ammo if you don't have any weapon in hand.

**Comment by Mauro-the-Wizard** [comment]
I'm an older wzs player and I would like to get old thing returned what means if you have only ONE  weapon eg. baikal like I had, but you don't hold it in your hands (you are holding a knife) you would recieve  7.62 ammo from a resupply box. If you are holding 2 or more weapons, you should get ammo for weapon you are holding in hands and if you are not holding any of weapons you should get random ammo for one weapon you have.

**Comment by Mauro-the-Wizard** [comment]
Btw what about picking up food from fridge?

**Comment by Azurblau** [comment]
Resupply no longer gives ammo if no weapon in hand, fridge no longer cools down when used while having everything.
