### ISSUE TITLE
[SUGGESTION] WZS: Nerf Puke Puss 

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#83]
Nerf its puke range alittle. 12 Feet seem alittle overkill in my opinion. Makes it impossible to defend small rooms or hallways that are not very wide. Or give its rate of fire a nerf instead.

**Comment by WardenPotato** [comment]
Im not really in for nerfing the pukepus because its essential in 50 player cades to break through. Although i do see its OP with lower playercounts and solo cades. I would rather see a scaling of all the bosses their effectiveness than having the pukepuss be nerfed
