### ISSUE TITLE
[Suggestion] WZS: Balance low population

### ISSUE THREAD

**Issue by Loickun** [Azurblau/Zombies.Zone#85]
Bosses are completly unfair when there are only 8 Players online or less.
My suggestion here now is to balance this scenario alittle. Why? Because if you want to Zmain do it when there 40 players online and its balanced, lets be honest.

My idea is to disable the Boss for the first 2 or 3 Waves. So Humans have a possible time window where they can cade without getting mowed down by a petrisis Baron or Puke puss in wave 2.
(I already know Zmainers are going to down vote this)

Scenario: 
If there are less than 10 Players total (7 Humans and 3 possible Zmainer) there wont be a boss spawn untill Wave 3. After that Zmainers can have their Boss.

If there is more than 14 Players zombies will get their first Boss at Wave 2 as normal.
This change is ment to only apply around the time when there are 4 to 8 people on the server and want to have fun in their kleiner cades. 

I understand Zmaining is one way to play the game. But its honestly only fun for 1 person in all the given scenarios I mentioned. Everyone else might very well not have a great time with Zmainers who grind for ez XP.

**Comment by Azurblau** [comment]
#69 
"Merging" this issue with the other by referencing it there and closing this one.
