### ISSUE TITLE
[SUGGESTION] WZS: Cooldown for healing items

### ISSUE THREAD

**Issue by WardenPotato** [Azurblau/Zombies.Zone#90]
Its all in the name, give the healing items a cooldown so they dont get spammed. its basically godmode for humans if they got a bit of points.

**Comment by jems01** [comment]
And/or
Disable use of zs_purchaseitems outside of F2 or Arsenal.

**Comment by CWorm** [comment]
I would add penalty of reducing max health for humans each time they use adrenaline or painkillers, and I'd remove healing grenades as well considering people use them more for solo healing than group healing, since Guardian exists they are close to being obsolete.
