### ISSUE TITLE
[SUGGESTION] WZS: Make dedicated medics more viable/important

### ISSUE THREAD

**Issue by Azurblau** [Azurblau/Zombies.Zone#93]
Options include:
- Make self-healing items (painkillers, etc.) less viable in cades, such as requiring distance travelled as a cooldown.
- Max health decreases by 5 on each use of painkillers and adrenaline and a medic can restore max health of others, requiring runners to visit medics.
- Remove heal grenade and decrease cooldown on healing-others on medkit.

I'd like to hear your opinions and suggestions.

**Comment by TheFray89** [comment]
In my opinion, removing medical grenades would make no sense, but changing their mechanics could give a huge improvement to their use.
soon I will suggest a mechanic that might interest you.

**Comment by WardenPotato** [comment]
+1 great idea

**Comment by CWorm** [comment]
Healing grenades need to be removed due to them being obsolete right now, and to think of the medic buff, maybe a small info box telling distance to nearest medic if player has less than 50% HP?

**Comment by CWorm** [comment]
As from newsfeed Discord chat: 

> - Removed Healing Grenade
> - Adrenaline now works longer and gives more health, but each use reduces max health by 15
> - Painkillers now give almost twice the health, but each use reduces max health by 10

It's an extreme measure but we will see how that will work out

**Comment by Azurblau** [comment]
Medkits should increase max health up to a maximum of 100.

I'll also consider adding an over-head icon for medics (people with medkits, lazarus or guardian) to make them easier to find.
